export default {
  Home: 'Home Page',
  drawerHome: 'Home Page',
  Account: 'Dont have an account? Click here to Sign Up',
  Welcome: 'Welcome to the Home Page',
  Access: 'Access Api Page Here',
  Acess_two: 'Access Api Page Two Here',
  AccessThree: 'Access Api Page Three Here',
  Accessbutton: 'Api Page',
  AccessbuttonTwo: 'Api Page Two',
  AccessbuttonThree: 'Api Page Three',
  Counter_App: 'Counter App',
  Map_App: 'Google Map',
  About: 'About Page',
  drawerAbout: 'About Page',
  Contact: 'Contact Page',
  drawerContact: 'Contact Page',
  Login: 'Log in',
  SignUp: 'SignupPage',
  logout: 'Sign Out',
  ApiPage: 'ApiPage',
  ApiPageTwo: 'ApiPageTwo',
  ApiPageThree: 'ApiPageThree',
  asynStorage: 'asynStorage',
  callNumber: 'callNumber',
  Camera: 'Camera',
  firstPage: 'FirstPage',
  secondPage: 'SecondPage',
  ThirdPage: 'ThirdPage',
  Counter: 'Counter',
  MapApi: 'MapApi',
  Signup: 'Sign up',
  SignUpAccount: 'Already Registered?Click here to Log in  ',
  welcomeAbout: 'Welcome to the About Page',
  openCamera: 'Open Camera',
  callNumber: 'Call Number',
  AsynStorage: 'Async Storage',
  interceptor: 'Interceptor Stack'


}