export default {
  Home: 'ہوم پیج',
  drawerHome: 'ہوم پیج',
  Account: 'اکاؤنٹ نہیں ہے؟ سائن اپ کرنے کے لیے یہاں کلک کریں۔',
  Welcome: 'ہوم پیج میں خوش آمدید',
  Access: 'یہاں Api صفحہ تک رسائی حاصل کریں',
  Acess_two: 'Api صفحہ ٹو یہاں تک رسائی حاصل کریں۔',
  AccessThree: 'Api صفحہ تھری تک رسائی حاصل کریں۔',
  Accessbutton: 'اے پی آئی پیج',
  AccessbuttonTwo: 'اے پی آئی پیج ٹو',
  AccessbuttonThree: 'اے پی آئی پیج تھری',
  Counter_App: 'کاؤنٹر اے پی',
  Map_App: 'گوگل کا نقشہ',
  About: 'کے بارے میں',
  drawerAbout: 'کے بارے میں',
  Contact: 'رابطہ کریں۔',
  drawerContact: 'رابطہ کریں۔',
  Login: ' لاگ ان کریں',
  Signup: 'سائن اپ پیج',
  logout: 'باہر جائیں',
  ApiPage: 'اے پی آئی ',
  ApiPageTwo: 'اے پی آئی پیج ٹو',
  ApiPageThree: 'اے پی آئی پیج تھری',
  asynStorage: ' اسٹوریج',
  callNumber: 'رابطکال نمبر',
  Camera: ' کیمرہ',
  firstPage: 'پہلا صفحہ',
  secondPage: 'وسرا صفحہ',
  ThirdPage: 'تیسرا صفحہ',
  Counter: 'کاؤنٹر',
  SignUpAccount: 'سائن اپ اکاؤن پہلے سے رجسٹرڈ ہے؟ لاگ ان کرنے کے لیے یہاں کلک کریں',
  welcomeAbout: 'کے بارے میں صفحہ میں خوش آمدید',
  openCamera: 'کیمرہ کھولیں',
  callNumberTwo: 'رابطکال نمبر',
  AsynStorage: 'اسٹوریج',
  interceptor: 'انٹرسیپٹر اسٹیک'

}